name: ASP.NET Core MVC CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CICD/CICD.csproj

    - name: Build application
      run: dotnet build CICD/CICD.csproj --no-restore --configuration Release

    - name: Test application
      run: dotnet test CICD/CICD.csproj --no-build --configuration Release

    - name: Publish application
      run: dotnet publish CICD/CICD.csproj --configuration Release --output ./publish

    - name: Upload published application
      uses: actions/upload-artifact@v4
      with:
        name: cicd-mvc-app
        path: ./publish